name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2020-05-16
version: '9.0.0-beta3'
project: 'drupal'
datestamp: 1589587978
